### ISSUE TITLE
'CoreFoundation.h' file not found

### ISSUE THREAD

**Issue by perfaram** [samdmarshall/OSXPrivateSDK#14] opened 2015-06-20 16:20 UTC
When including OSXPrivateSDK as an additional framework, Xcode seems to messes up and stops searching for headers in the main framework... As such, every "standard" headers are marked as *not found* (CoreFoundation, Foundation, etc...).

I tried cleaning cache, to no avail. Any idea ?

**Comment by perfaram** [comment] 2015-06-20 16:23
OK... Missed the "isystem" part of README. However...what should I "remove" ?

**Comment by samdmarshall** [comment] 2015-06-20 18:12
you may need to add your own `-iframework /*project_root*/PrivateSDKs/PrivateSDK10.10.sparse.sdk/System/Library/Frameworks/` and  `-iframework /*project_root*/PrivateSDKs/PrivateSDK10.10.sparse.sdk/System/Library/PrivateFrameworks/` flags to `OTHER_CFLAGS` for it to register those headers. there is some wonky behavior with auto-determining search paths, I currently have radars open to fix these.

**Comment by perfaram** [comment] 2015-06-20 20:03
Unfortunately, that only helps for files belonging to the project. Now, I get the same error in Foundation

**Comment by samdmarshall** [comment] 2015-06-20 22:13
can you upload a sample project so i can try to reproduce this behavior?

**Comment by joevt** [comment] 2015-08-16 09:08
`configd-699.1.5` from Apple Open Source might be a useful sample project to test this sparse SDK problem.

I'm trying to build the scutil target using the command `xcodebuild -target scutil`

Using the sparse SDK as an additional framework gives an error:
`'CoreFoundation/CoreFoundation.h' file not found`

Not using the sparse SDK gives an error (only for tests.c):
`'CoreFoundation/CFRuntime.h' file not found`

CFRuntime.h is private. CoreFoundation.h is not. The sparse SDK only includes the private files. Xcode is not searching the bask SDK for the non-private files.

**Comment by samdmarshall** [comment] 2015-08-16 15:54
I looked into this and it seems to be caused by a bug in how Xcode's build system resolves frameworks based on where/which SDK they were found in. I have a radar open on this but for now i've pushed a fix to the repo and using the following command:

`xcodebuild -target scutil ADDITIONAL_SDKS="~/Projects/OSXPrivateSDK/PrivateSDK10.10.sparse.sdk" USER_HEADER_SEARCH_PATHS="~/Projects/OSXPrivateSDK/PrivateSDK10.10.sparse.sdk/usr/local/include dnsinfo Plugins/common SystemConfiguration.fproj"`

I was able to get the utility to build without issue, let me know if this resolves the problem.

**Comment by joevt** [comment] 2015-08-22 23:30
Thanks, those changes made it possible to build that project with that command without modifying the project or opening it in Xcode.

**Closed** 2015-08-23 18:03 UTC
